spring.application.name=balanceiq-backend
spring.datasource.url=jdbc:postgresql://balanceiq-db:5432/balanceiq
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=balanceiqsecretkeybalanceiqsecretkeybalanceiq
jwt.expiration=86400000

gemini.api.key=${GEMINI_API_KEY WRITE HERE}